### PR TITLE
Douplicated word and better readable sentence

### PR DESCRIPTION
**Pull request by petrisch**
Not shure if this is the right spot to do it directly in the html file.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
It needs to be done in the main BOLTS repository. You should make a PR over there. I created a issue. https://github.com/boltsparts/BOLTS/issues/259

I might copy it if I have a minute, but ATM there is a lot around.

**Comment by berndhahnebach** [comment]
https://github.com/boltsparts/boltsparts/commit/80bafb4fabec77e7dfdd2264ab938417455a5dcb

**Comment by petrisch** [comment]
Ah I wanted to do this on the weekend, you have been quicker than me 😄

**Comment by berndhahnebach** [comment]
Have a beer instead :-)

FYI for further BOLTS development ... BOLTS repo has been moved to archive and has been reinitialized. For more information see https://github.com/boltsparts/BOLTS_archive/issues/163

**Pull request closed without merging**
